USE RFA;
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A00.0', 'Cholera due to Vibrio cholerae 01, biovar cholerae', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A00.1', 'Cholera due to Vibrio cholerae 01, biovar eltor', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A00.9', 'Cholera, unspecified', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A01.1', 'Paratyphoid fever A', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A01.2', 'Paratyphoid fever B', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A01.3', 'Paratyphoid fever C', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A01.4', 'Paratyphoid fever, unspecified', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A01.00', 'Typhoid fever, unspecified', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A01.01', 'Typhoid meningitis', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A01.02', 'Typhoid fever with heart involvement', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A01.03', 'Typhoid pneumonia', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A01.05', 'Typhoid osteomyelitis', NOW(), NOW());
INSERT INTO Diagnoses (code, diagnosis, createdAt, updatedAt) VALUES ('A01.09', 'Typhoid fever with other complications', NOW(), NOW());